apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: flink
  namespace: argocd
spec:
  destination:
    namespace: flink
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: flink-kubernetes-operator
    repoURL: https://downloads.apache.org/flink/flink-kubernetes-operator-1.7.0/
    targetRevision: 1.7.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
