apiVersion: v1
kind: Service
metadata:
  name: echo-header
  labels:
    app: echo-header
    service: echo-header
spec:
  ports:
  - port: 8090
    name: http
  selector:
    app: echo-header
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo-header
  labels:
    account: echo-header
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-header-v1
  labels:
    app: echo-header
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-header
      version: v1
  template:
    metadata:
      labels:
        app: echo-header
        version: v1
    spec:
      serviceAccountName: echo-header
      containers:
      - name: echo-header 
        image: markmckie123/header-echo-x86-64:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090
        securityContext:
          runAsUser: 1000
        resources:
          limits:
            memory: 128M
          requests:
            cpu: 100m
            memory: 128M 

