apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-kubernetes-operator
  namespace: argocd
spec:
  destination:
    namespace: apache-flink
    server: https://kubernetes.default.svc
  project: local-cluster
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: flink-kubernetes-operator
    repoURL: https://github.com/markmckie/local-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true