apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink
  namespace: argocd
spec:
  destination:
    namespace: flink
    server: https://kubernetes.default.svc
  project: local-cluster
  source:
    chart: flink-kubernetes-operator
    repoURL: https://downloads.apache.org/flink/flink-kubernetes-operator-0.1.0/
    targetRevision: 0.1.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
