apiVersion: v1
kind: Secret
metadata:
  name: repo-172605416
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
data:
  project: ZGVmYXVsdA==
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL21hcmttY2tpZS9sb2NhbC1jbHVzdGVyLmdpdA==
type: Opaque
